version: '3.8'

networks:
  distributed:
    driver: bridge

services:
  # P2P Node for node1
  distributed-node1:
    image: distributed:latest
    container_name: distributed-node1
    hostname: node1
    networks:
      distributed:
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
    environment:
      DISTRIBUTED_NODE_ID: "node1"
      DISTRIBUTED_NODE_GEO_LOCATION: "eu-central"
      DISTRIBUTED_P2P_LISTEN_ADDRS: "/ip4/0.0.0.0/tcp/4001"
      DISTRIBUTED_P2P_ENABLE_MDNS: "false"
      DISTRIBUTED_P2P_ENABLE_DHT: "true"
      DISTRIBUTED_P2P_BOOTSTRAP_PEERS: ""
      DISTRIBUTED_WIREGUARD_ENABLED: "false"
      DISTRIBUTED_LLM_BACKEND: "llamacpp"
      # Connect to 1 local llama server
      DISTRIBUTED_LLM_LLAMACPP_URLS: "http://host.docker.internal:8080/v1"
      DISTRIBUTED_LLM_MODEL_ID: "llama-3.1-8b"
      DISTRIBUTED_GATEWAY_ENABLED: "false"
      DISTRIBUTED_LOG_LEVEL: "debug"
    ports:
      - "4001:4001"      # P2P
      - "9090:9090"      # Metrics
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - node1-p2p-data:/var/lib/distributed
      - /lib/modules:/lib/modules:ro
    restart: unless-stopped

volumes:
  node1-p2p-data: